### ISSUE TITLE
Issue with kuksa-client, connection problem with kuksa server

### ISSUE THREAD

**Issue by kulta4** [eclipse-kuksa/kuksa-python-sdk#16]
Hi,
    I unable to connect the kuksa-client(python) with kuksa databroker, I already raised a ticket, and I would like to mention the same here. please refer the like "https://github.com/eclipse/kuksa.val/issues/733" to redirect. Thank you.

**Comment by erikbosch** [comment]
As discussed in referenced issue  connection problem was due to wring arguments. Closing this one, please reopen if needed
